In [1]:
import pandas as pd

In [2]:
import re

In [4]:
from nltk.tokenize import word_tokenize

In [3]:
from nltk.corpus import stopwords

In [6]:
from nltk.stem import PorterStemmer

NameError: name 'df' is not defined

Error in loading the data: [Errno 2] No such file or directory: 'NLP_dataset'

NameError: name 'csv' is not defined

In [15]:
import csv

df = pd.read_csv("/kaggle/input/datasets/faheemrasool12/nlp-dataset/02) IMDB Dataset.csv", 
                 encoding='latin-1',
                 engine='python',
                 on_bad_lines='skip',
                 quotechar='"',
                 quoting=csv.QUOTE_MINIMAL)

print(df.shape)  # Kitni rows load hui check karo
print(df.head())

(50020, 2)
                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.shape

(49602, 2)

In [20]:
df["review"]=df["review"].str.lower()

In [32]:
def remove_url(text):
    return re.sub(r"http\S+","",text)
df["review"]=df["review"].apply(remove_url)

In [27]:
def remove_html(text):
    return re.sub(r"<.*?>","",text)
df["review"]=df["review"].apply(remove_html)

In [30]:
def remove_punct(text):
    return re.sub(r"[^A-Za-z0-9\s]","",text)
df["review"]=df["review"].apply(remove_punct)

In [34]:
df.info

<bound method DataFrame.info of                                                   review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
50015  i thought this movie did a down right good job...  positive
50016  bad plot bad dialogue bad acting idiotic direc...  negative
50017  i am a catholic taught in parochial elementary...  negative
50018  im going to have to disagree with the previous...  negative
50019  no one expects the star trek movies to be high...  negative

[49602 rows x 2 columns]>

In [36]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=set(stopwords.words("english"))
    filtered_text=[word for word in tokens if word not in stop_words]
    return"".join(filtered_text)
df["review"]=df["review"].apply(remove_stopwords)

In [37]:
df

                                                  review sentiment
0      onereviewersmentionedwatching1ozepisodeyoullho...  positive
1      wonderfullittleproductionfilmingtechniqueunass...  positive
2      thoughtwonderfulwayspendtimehotsummerweekendsi...  positive
3      basicallytheresfamilylittleboyjakethinkstheres...  negative
4      pettermatteislovetimemoneyvisuallystunningfilm...  positive
...                                                  ...       ...
50015  thoughtmovierightgoodjobwasntcreativeoriginalf...  positive
50016  badplotbaddialoguebadactingidioticdirectingann...  negative
50017  catholictaughtparochialelementaryschoolsnunsta...  negative
50018  imgoingdisagreepreviouscommentsidemaltinonesec...  negative
50019  oneexpectsstartrekmovieshighartfansexpectmovie...  negative

[49602 rows x 2 columns]

In [40]:
def stemming(text):
    ps=PorterStemmer()
    tokens=word_tokenize(text)
    return"".join(ps.stem(token) for token in tokens)
df["review"]=df["review"].apply(stemming)

In [41]:
df

                                                  review sentiment
0      onereviewersmentionedwatching1ozepisodeyoullho...  positive
1      wonderfullittleproductionfilmingtechniqueunass...  positive
2      thoughtwonderfulwayspendtimehotsummerweekendsi...  positive
3      basicallytheresfamilylittleboyjakethinkstheres...  negative
4      pettermatteislovetimemoneyvisuallystunningfilm...  positive
...                                                  ...       ...
50015  thoughtmovierightgoodjobwasntcreativeoriginalf...  positive
50016  badplotbaddialoguebadactingidioticdirectingann...  negative
50017  catholictaughtparochialelementaryschoolsnunsta...  negative
50018  imgoingdisagreepreviouscommentsidemaltinonesec...  negative
50019  oneexpectsstartrekmovieshighartfansexpectmovie...  negative

[49602 rows x 2 columns]

In [43]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [45]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["sentiment"]=le.fit_transform(df["sentiment"])

In [46]:
df

                                                  review  sentiment
0      onereviewersmentionedwatching1ozepisodeyoullho...          9
1      wonderfullittleproductionfilmingtechniqueunass...          9
2      thoughtwonderfulwayspendtimehotsummerweekendsi...          9
3      basicallytheresfamilylittleboyjakethinkstheres...          8
4      pettermatteislovetimemoneyvisuallystunningfilm...          9
...                                                  ...        ...
50015  thoughtmovierightgoodjobwasntcreativeoriginalf...          9
50016  badplotbaddialoguebadactingidioticdirectingann...          8
50017  catholictaughtparochialelementaryschoolsnunsta...          8
50018  imgoingdisagreepreviouscommentsidemaltinonesec...          8
50019  oneexpectsstartrekmovieshighartfansexpectmovie...          8

[49602 rows x 2 columns]

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
tfidf=TfidfVectorizer(max_features=5000)
X=tfidf.fit_transform(df["review"]).toarray()
y=df["sentiment"].values